version: '3'

services:
  keycloak-db:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      - PGDATA=/var/lib/postgresql
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - bridgebook-ai

volumes:
  db-data:

networks:
  bridgebook-ai:
    external: true